### ISSUE TITLE
很有意思的项目，如有需要帮助的欢迎提出

### ISSUE THREAD

**Issue by lni** [motecshine/RaftSqlite3#1]
我曾想做个类似的，但一直在给dragonboat加功能而没有时间去做。

如果有dragonboat方面任何问题，欢迎提出，会迅速解答。谢谢！

**Comment by motecshine** [comment]
谢谢 只是实现性的项目, 最近 在做 tidb 的作业.

**Comment by lni** [comment]
sqlite加一致性必然只是试验性的demo项目，但会是很好的一个demo。

有任何疑问可直接提issue。demo能实现基本的sqlite状态的复制后，如果可以，我想在dragonboat的README里链接，也可以帮助完善。谢谢！
